sudo: require
services:
        - docker

before_install:
        - docker build -t andreisimi/docker-react-tutorial -f Dockerfile.dev .


script:
        - docker run -e CI=true andreisimi/docker-react-tutorial npm run test -- --coverage 
